- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
    requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hrs # Meow-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs # Meow-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs # Meow-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 27000 # 7.5 hours
    - !type:OverallPlaytimeRequirement
      time: 251000 #70 hrs # Meow-RoleTime
  setPreference: false
  startingGear: CentcomGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
