- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxSplit
  - CorvaxTerra
  - CorvaxFrame
  - CorvaxPearl
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Europa
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train
